git clone https://github.com/sneedcord/css-mediaquery.git css-mediaquery
git clone https://github.com/sneedcord/docker.git docker
git clone https://github.com/sneedcord/sneedcord.git sneedcord
git clone https://github.com/sneedcord/sneedcord-client.git client
git clone https://github.com/sneedcord/sneedcord-client-native.git client-native
git clone https://github.com/sneedcord/sneedcord-docs.git docs
git clone https://github.com/sneedcord/sneedcord-landingpage.git landingpage
git clone https://github.com/sneedcord/sneedcord-plugins.git plugins
git clone https://github.com/sneedcord/sneedcord-server.git server
git clone https://github.com/sneedcord/sneedcord-themes.git themes
git clone https://github.com/sneedcord/sneedcord-ui.git ui
git clone https://github.com/sneedcord/sneedcord-voice-gateway.git voice-gateway
git clone https://github.com/sneedcord/sneedcord.js.git sneedcord.js
git clone https://github.com/sneedcord/sneedcord.js-builders.git sneedcord.js-builders
git clone https://github.com/sneedcord/sneedcord.py.git sneedcord.py
git clone https://github.com/sneedcord/react-native-withcss.git react-native-withcss
